name: SAML Sample App DAST Scan

on:
  workflow_dispatch:
    inputs:
      running_environment:
        description: 'Environment'
        required: true
        default: 'dev'
        
env:
  ENVIRONMENT_SITE: "www.example.com"
  
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan SAML Sample app
    steps:
        - name: if dev
          run: echo ${{ inputs.running_environment }}
          if: inputs.running_environment == 'dev'
#          run: echo 'in dev' | ${ENVIRONMENT_SITE} = "www.dev.com"
        - name: if staging
          if: inputs.running_environment == 'staging'
          run: echo "we're in staging"
        - name: ZAP Scan
          run: 
            echo ${ENVIRONMENT_SITE}
#           uses: zaproxy/action-full-scan@v0.3.0
#           with:
#             token: ${{ secrets.GITHUB_TOKEN }}
#             docker_name: 'owasp/zap2docker-stable'
#             target: Environment_Site
#             rules_file_name: '.zap/rules.tsv'
#             cmd_options: '-a'

