name: SAML Sample App DAST Scan

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'dev'
        
env:
  ENVIRONMENT_SITE: "www.example.com"
  
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan SAML Sample app
    steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            ref: master
        - name: Set Environment Site
          run:
            :if [[ inputs.environment == 'dev' ]]; then
              echo "we're in dev"
            else
              echo "we're not in dev"
            fi
        - name: ZAP Scan
          run: 
            echo ENVIRONMENT_SITE
#           uses: zaproxy/action-full-scan@v0.3.0
#           with:
#             token: ${{ secrets.GITHUB_TOKEN }}
#             docker_name: 'owasp/zap2docker-stable'
#             target: Environment_Site
#             rules_file_name: '.zap/rules.tsv'
#             cmd_options: '-a'

